CREATE TABLE users(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
user_id VARCHAR(50)  UNIQUE NOT  NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR (255)  NOT NULL,
role VARCHAR (100) NOT NULL,
status VARCHAR(50) NOT NULL,
clearance_level INT DEFAULT 1,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);