CREATE TABLE elections(
id BIGINT  AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(200) NOT NULL UNIQUE,
description TEXT ,
status VARCHAR (50) NOT NULL,
start_date TIMESTAMP NOT NULL,
end_date TIMESTAMP NOT NULL,
created_by VARCHAR NOT NULL,

created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 CONSTRAINT check_election_status CHECK (UPPER (status)IN ('UPCOMING','ONGOING','CLOSED','PUBLISHED','FAILED')),
 CONSTRAINT fk_election_creator  FOREIGN KEY(created_by) REFERENCES users(id)
);