CREATE TABLE parties(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) UNIQUE NOT NULL,
symbol VARCHAR(100) UNIQUE NOT NULL,
description TEXT ,
founded_year INT,
created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
