CREATE TABLE audit(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
action VARCHAR(100) NOT NULL,
status VARCHAR(20) NOT NULL,
reason TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
prev_hash VARCHAR(255),
entry_hash VARCHAR(255),
 CONSTRAINT fk_data_editor FOREIGN KEY(user_id) REFERENCES users(id)
);